### ISSUE TITLE
GitHub API changed?

### ISSUE THREAD

**Issue by djjudas21** [camptocamp/puppetfile-updater#15]
Calls to the GitHub API are returning 404 not found.

```
[jg4461@it050546 resnet-puppet]$ rake update
rake aborted!
Octokit::NotFound: GET https://api.github.com/repos/resnet/puppet-addressspace/commits: 404 - Not Found // See: https://developer.github.com/v3
/usr/local/share/gems/gems/octokit-4.7.0/lib/octokit/response/raise_error.rb:16:in `on_complete'
/usr/local/share/gems/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
/usr/local/share/gems/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
/usr/local/share/gems/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
/usr/local/share/gems/gems/octokit-4.7.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
/usr/local/share/gems/gems/octokit-4.7.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
/usr/local/share/gems/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/usr/local/share/gems/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/usr/local/share/gems/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
/usr/local/share/gems/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
/usr/local/share/gems/gems/octokit-4.7.0/lib/octokit/connection.rb:156:in `request'
/usr/local/share/gems/gems/octokit-4.7.0/lib/octokit/connection.rb:84:in `paginate'
/usr/local/share/gems/gems/octokit-4.7.0/lib/octokit/client/commits.rb:29:in `commits'
/usr/local/share/gems/gems/puppetfile-updater-0.4.0/lib/puppetfile-updater/task.rb:83:in `block (3 levels) in define'
/usr/local/share/gems/gems/puppetfile-updater-0.4.0/lib/puppetfile-updater/task.rb:73:in `each'
/usr/local/share/gems/gems/puppetfile-updater-0.4.0/lib/puppetfile-updater/task.rb:73:in `block (2 levels) in define'
/usr/local/share/gems/gems/ruby-augeas-0.5.0/lib/augeas.rb:51:in `open'
/usr/local/share/gems/gems/puppetfile-updater-0.4.0/lib/puppetfile-updater/task.rb:55:in `block in define'
/usr/share/gems/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => update
(See full trace by running task with --trace)
```

**Comment by djjudas21** [comment]
Am running octokit 4.7.0

**Comment by djjudas21** [comment]
Looks like this is not a bug with this project, closing

**Comment by blackknight36** [comment]
@djjudas21 What was the solution?  I'm also getting this error when running the sync_refs task.
